"""add image_url to package

Revision ID: 884d48d39d24
Revises: eae02fb5a269
Create Date: 2025-07-16 23:21:30.747562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884d48d39d24'
down_revision = 'eae02fb5a269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
