"""Add updated_topup_for column to orders

Revision ID: b030d90429db
Revises: 6b018bb3d6a0
Create Date: 2025-07-21 14:47:59.768866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b030d90429db'
down_revision = '6b018bb3d6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topup_for', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('topup_for')

    # ### end Alembic commands ###
